# Generated by Django 3.0.5 on 2020-05-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Is active'),
        ),
    ]
