dist: xenial
services:
  - postgresql
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential gettext python-dev zlib1g-dev libpq-dev xvfb
  - sudo apt-get install -qq libjpeg8-dev libfreetype6-dev libwebp-dev
  - sudo apt-get install -qq graphviz-dev python-setuptools python3-dev python-virtualenv python-pip
  - sudo apt-get install -qq firefox automake libtool libreadline6 libreadline6-dev libreadline-dev
  - sudo apt-get install -qq libsqlite3-dev libxml2 libxml2-dev libssl-dev libbz2-dev wget curl llvm
before_script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
language: python
python:
  - "3.8"
install:
  - pip install -r requirements/local.txt
script:
  - "pytest"
cache: pip
env:
  - DATABASE_URL=postgres://postgres@localhost/test_db CELERY_BROKER_URL=redis://redis:6379/0 CACHE_URL=redis://redis:6379/1
